insert into book_table (book_title, quantity, version) values ('America the Beautiful 2', 36, 1);
insert into book_table (book_title, quantity, version) values ('White Squall', 40, 1);
insert into book_table (book_title, quantity, version) values ('Destiny', 32, 1);
insert into book_table (book_title, quantity, version) values ('Vengeance (Fuk sau)', 52, 1);
insert into book_table (book_title, quantity, version) values ('Up the Down Staircase', 61, 1);
insert into book_table (book_title, quantity, version) values ('Liberty Stands Still', 41, 1);
insert into book_table (book_title, quantity, version) values ('The Vixen', 42, 1);
insert into book_table (book_title, quantity, version) values ('Barkleys of Broadway, The', 46, 1);
insert into book_table (book_title, quantity, version) values ('Bride of Frankenstein', 63, 1);
insert into book_table (book_title, quantity, version) values ('Hava Nagila: The Movie', 13, 1);
insert into book_table (book_title, quantity, version) values ('Repo! The Genetic Opera', 69, 1);
insert into book_table (book_title, quantity, version) values ('Sin Nombre', 65, 1);
insert into book_table (book_title, quantity, version) values ('Brother of Sleep (Schlafes Bruder)', 80, 1);
insert into book_table (book_title, quantity, version) values ('Guilty (Présumé coupable)', 24, 1);
insert into book_table (book_title, quantity, version) values ('Jar, The (Khomreh)', 63, 1);
insert into book_table (book_title, quantity, version) values ('In Harm''s Way', 70, 1);
insert into book_table (book_title, quantity, version) values ('Fantasia', 29, 1);
insert into book_table (book_title, quantity, version) values ('Nanny McPhee Returns', 82, 1);
insert into book_table (book_title, quantity, version) values ('Ghosts of Cité Soleil', 48, 1);
insert into book_table (book_title, quantity, version) values ('Runaway Train', 72, 1);
insert into book_table (book_title, quantity, version) values ('Lucky Break', 51, 1);
insert into book_table (book_title, quantity, version) values ('Escape (Flukt)', 77, 1);
insert into book_table (book_title, quantity, version) values ('Beyond the Stars', 42, 1);
insert into book_table (book_title, quantity, version) values ('Idiocracy', 100, 1);
insert into book_table (book_title, quantity, version) values ('Internship, The', 98, 1);
insert into book_table (book_title, quantity, version) values ('Bionicle', 74, 1);
insert into book_table (book_title, quantity, version) values ('Natural, The', 82, 1);
insert into book_table (book_title, quantity, version) values ('Houdini', 67, 1);
insert into book_table (book_title, quantity, version) values ('Recruit, The', 39, 1);
insert into book_table (book_title, quantity, version) values ('Black Dog', 98, 1);
insert into book_table (book_title, quantity, version) values ('Can''t Help Singing', 76, 1);
insert into book_table (book_title, quantity, version) values ('Hero', 17, 1);
insert into book_table (book_title, quantity, version) values ('Live!', 18, 1);
insert into book_table (book_title, quantity, version) values ('Executive Decision', 32, 1);
insert into book_table (book_title, quantity, version) values ('Africa Screams', 62, 1);
insert into book_table (book_title, quantity, version) values ('Babe Ruth Story, The ', 95, 1);
insert into book_table (book_title, quantity, version) values ('Shenandoah', 16, 1);
insert into book_table (book_title, quantity, version) values ('War', 95, 1);
insert into book_table (book_title, quantity, version) values ('Satan''s Tango (Sátántangó)', 96, 1);
insert into book_table (book_title, quantity, version) values ('Landet som icke är', 58, 1);
insert into book_table (book_title, quantity, version) values ('Blackout', 92, 1);
insert into book_table (book_title, quantity, version) values ('Endangered Species', 35, 1);
insert into book_table (book_title, quantity, version) values ('Pilate and Others', 93, 1);
insert into book_table (book_title, quantity, version) values ('Mondo Hollywood', 81, 1);
insert into book_table (book_title, quantity, version) values ('House at the End of the Street', 13, 1);
insert into book_table (book_title, quantity, version) values ('Wild, Wild Planet', 56, 1);
insert into book_table (book_title, quantity, version) values ('In a Town This Size', 76, 1);
insert into book_table (book_title, quantity, version) values ('Captain America', 24, 1);
insert into book_table (book_title, quantity, version) values ('Ju-on: The Curse', 74, 1);
insert into book_table (book_title, quantity, version) values ('Man Push Cart', 12, 1);